#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

# (cd background && runApplication $(getApplication))

cd background || exit 1

runApplication decomposePar

runApplication mpirun -np 48 overInterDyMFoam -parallel

runApplication reconstructPar

rm -rf processor*

#------------------------------------------------------------------------------
